# Generated by Django 3.1.3 on 2020-11-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('codigo', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, unique=True)),
                ('cargaHoraria', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'disciplina',
            },
        ),
    ]
