# Generated by Django 3.1.3 on 2020-11-28 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='cursoAssociado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.curso'),
            preserve_default=False,
        ),
    ]
