# Generated by Django 3.1.3 on 2020-11-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedDeDados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeArquivo', models.CharField(db_index=True, max_length=100, unique=True)),
                ('dataCarregamento', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'feedDeDados',
            },
        ),
    ]
