# Generated by Django 3.1.3 on 2020-11-27 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedDeDados', '0002_auto_20201127_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeddedados',
            name='dataCarregamento',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
