# Generated by Django 3.1.3 on 2020-11-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='disciplinas',
            field=models.ManyToManyField(through='aluno.DisciplinaCursada', to='disciplina.Disciplina'),
        ),
    ]
