# Generated by Django 3.1.3 on 2020-11-30 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20201127_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
    ]
