# Generated by Django 3.1.3 on 2020-11-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('codigo', models.CharField(db_index=True, max_length=8, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'curso',
            },
        ),
    ]
